import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CT Gladiadores",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header> 
          <div className="espacamento-h1">
            <img src="/tcc-gladiadores.jpeg" height={100} width={100}/>
            <h1 className="titulo">CT GLADIADORES</h1>
          </div>

          <div className="divespacamentodelinhas">
            <a className="espaçamento" href="/">Página inicial</a> 
            <a className="espaçamento" href="../planos">Planos</a>
            <a className="espaçamento" href="../turmas">Turmas</a>
          </div>

          <div className="botao">
            <a href="../registro"><button className="button">Registrar</button></a>
          </div>
          <div className="botao1">
            <a href="../login"><button className="button">Logar</button></a>
          </div>            
        </header>

        <main>{children}</main>

        <footer className="footer">
          <div className="footer-container">
            <div className="footer-section">
              <h3>CT Gladiadores</h3>
              <p>Treinamento profissional para atletas de todas as idades. Venha conhecer nossas turmas e planos.</p>
            </div>

            <div className="footer-section">
              <h4>Contato</h4>
              <p>
                <img src="/whatsapp.png" alt="WhatsApp" className="footer-icon" />
                <a href="https://wa.me/558386333543" target="_blank">+55 83 98633-3543</a>
              </p>
              <p>
                <img src="/instagram.png" alt="Instagram" className="footer-icon" />
                <a href="https://instagram.com/ctgladiadores" target="_blank">@ctgladiadores</a>
              </p>
            </div>
          </div>

          <div className="footer-bottom">
            <p>© 2025 CT Gladiadores. Todos os direitos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
