import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header> 
          <div className="espacamento-h1">
            <img src = "tcc-gladiadores.jpeg" height={100} width={100}/>
            <h1 className="titulo">CT GLADIADORES</h1>
          </div>
            

            <div className="divespacamentodelinhas">
            
            <a className="espaçamento" href="../paginainicial">Página inicial</a> 
            <a className="espaçamento" href="../planos" style = {{color: 'gray'}}>Planos</a>
        
            </div>
            <div className="botao">
                    <a href="../registro"><button className="button">Registrar</button></a>
            </div>
            <div className="botao1">
                    <a href="../login"><button className="button">Logar</button></a>
            </div>            
        </header>{children}
      </body>
    </html>
  );
}
